add exit if test failed

diff --git a/bin/test-backend-ci b/bin/test-backend-ci
--- a/bin/test-backend-ci
+++ b/bin/test-backend-ci
@@ -36,6 +36,14 @@ main(){
 
 	check_exit "$?"
 
+	# we need to bomb out if there was an error
+	if [[ $exit_code -ne 0 ]]; then
+		echo
+		log "Errors occurred during script execution"
+	fi
+
+	exit "$exit_code"
+
     # then list through the folders and run the tests
     targets=("lib" "middleware" "models" "policies" "routes" "scopes" "services" "tools" "widgets") 
 
@@ -70,6 +78,14 @@ main(){
 			--forceExit
 
 			check_exit "$?"
+
+
+		    if [[ $exit_code -ne 0 ]]; then
+             echo
+            	log "Errors occurred during script execution"
+   			fi
+
+    		exit "$exit_code"
     done
 }
 
