CI should exit if there is an exit code

diff --git a/bin/test-backend-ci b/bin/test-backend-ci
--- a/bin/test-backend-ci
+++ b/bin/test-backend-ci
@@ -1,4 +1,13 @@
 #!/bin/bash
+declare lr=">>>>>>>>"
+declare -i exit_code=0
+
+check_exit() {
+    if [[ "$1" -ne 0 ]]; then
+        echo "$lr last docker-compose command failed"
+        ((exit_code++))
+    fi
+}
 
 main(){
     # first get the tests in the root directory
@@ -24,6 +33,8 @@ main(){
 		--coverageDirectory="$(pwd)"/coverage/src/root \
 		--collectCoverageFrom=src/*.js \
 		--forceExit
+
+	check_exit "$?"
 
     # then list through the folders and run the tests
     targets=("lib" "middleware" "models" "policies" "routes" "scopes" "services" "tools" "widgets") 
@@ -57,6 +68,8 @@ main(){
 			--coverageDirectory="$(pwd)"/coverage/src/"$target" \
 			--collectCoverageFrom=src/"$target"/**/*.js \
 			--forceExit
+
+			check_exit "$?"
     done
 }
 
