update pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,29 @@
 #!/usr/bin/env bash
 set -e
 
-
+common_changed=false
+frontend_yarn_lock_changed=false
+backend_yarn_lock_changed=false
 files=$(git diff --cached --name-only)
+
 for f in $files
 do
   
+  # check if packages/common/src/index.js was changed
+  if [ -e "$f" ] && [[ $f == packages/common/src/index.js ]]; then
+    common_changed=true
+  fi
+  
+  # check if frontend/yarn.lock was changed
+  if [ -e "$f" ] && [[ $f == frontend/yarn.lock ]]; then
+    frontend_yarn_lock_changed=true
+  fi
+  
+  # check if backend/yarn.lock was changed
+  if [ -e "$f" ] && [[ $f == backend/yarn.lock ]]; then
+    backend_yarn_lock_changed=true
+  fi
+
   # Format any *.tf files that were cached/staged
   if [ -e "$f" ] && [[ $f == *.tf ]]; then
     printf "Pre-Commit Git Hook Running: 'terraform fmt' \n\n"
@@ -25,3 +43,11 @@ do
     git add "$f"
   fi
 done
+
+if [ $common_changed ]; then
+  echo "Common changed"
+  if [ $frontend_yarn_lock_changed = false ] || [ $backend_yarn_lock_changed = false ]; then
+    echo "ERROR: common/index.js was changed, but yarn.lock was not updated. Please run 'yarn deps' in the frontend and backend directories."
+    exit 1
+  fi
+fi
