local docker

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -41,55 +41,57 @@ tasks:
     vars:
       STACK: '{{default .DEV_DEBUG .STACK}}'
     cmds:
-      - yarn deps:install
-      - yarn build
-
       - |
         echo "Starting stack..."
-        SUCCESS=false
         docker compose -f {{.COMPOSE_FILE}} {{.STACK}} build
-        docker compose -f {{.COMPOSE_FILE}} {{.STACK}} up --detach --wait && SUCCESS=true
-        if [ "$SUCCESS" = false ]; then
-          # get logs from any unhealthy containers to debug
-          docker ps --filter "health=unhealthy" --format '{{.ID}} {{.Names}}' |
-          while read -r id name; do
-            echo "===== $name ($id) failed ====="
-            docker logs -n 50 "$id"
-          done
-          exit 1;
-        fi
+        docker compose -f {{.COMPOSE_FILE}} {{.STACK}} up --detach --wait || \
+          (docker compose -f {{.COMPOSE_FILE}} logs -n 25 && \
+            docker ps && \
+            echo "Stack failed to start." && exit 1)
       - cmd: docker compose -f {{.COMPOSE_FILE}} logs -n 100
       - cmd: docker compose -f {{.COMPOSE_FILE}} logs --follow
         ignore_error: true
-
-  # --- Stack Down ---
 
   stack-down:
     desc: Stop compose stacks for this repo
     cmds:
       - docker compose -f {{.COMPOSE_FILE}} --profile fullstack down --remove-orphans
 
+  refresh:
+    desc: Rebuild frontend and backend code, reinstall deps, restart stack
+    cmds: 
+      - task: stack-down
+      - task: rebuild
+      - task: migrate
+      - task: reseed
+      - task: stack-up
+
+  reset:
+    desc: Delete all containers, images, networks, volumes and reinitialize stack
+    cmds:
+      - task: stack-down
+      - cmd: docker compose -f {{.COMPOSE_FILE}} down --volumes --rmi all --remove-orphans
+      - task: refresh
+
+  # --- Utility ---
+
+  rebuild:
+    desc: Rebuild frontend and backend code
+    cmds:
+      - yarn deps:install
+      - yarn build
+      - docker compose -f {{.COMPOSE_FILE}} build --no-cache
+
+  migrate:
+    desc: Run database migrations
+    cmds:
+      - docker compose -f {{.COMPOSE_FILE}} run --rm backend yarn db:migrate
+
   reseed:
     desc: Reseed the database via testing server
     cmds:
       - docker compose -f {{.COMPOSE_FILE}} up --detach --wait testingonly
       - curl http://localhost:9999/testingOnly/reseed
-
-  refresh:
-    desc: Rebuild frontend and backend code, reinstall deps, restart stack
-    cmds: 
-      - task: stack-down
-      - task: reseed
-      - docker compose -f {{.COMPOSE_FILE}} build --no-cache
-      - task: stack-up
-
-  reset:
-    desc: Remove containers, images, networks, volumes and reinitialize stack
-    cmds:
-      - task: stack-down
-      - docker compose -f {{.COMPOSE_FILE}} down --volumes --rmi all --remove-orphans
-
-  # --- Utility ---
 
   stack-logs:
     desc: Tail current running stack logs
