testing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -532,6 +532,9 @@ jobs:
     - run:
         name: Build frontend assets
         command: yarn --cwd frontend run build
+    - notify_slack:
+        message_text: "testing"
+        slack_channel: "tm-test"
     - cf_deploy:
         target_env: << parameters.target_env >>
     - write_envs:
@@ -549,10 +552,6 @@ jobs:
             if [ << parameters.target_env >> == "prod" || << parameters.target_env >> == "staging" ]; then
               ./bin/notify-slack.sh "${msg}" acf-head-start-alerts ${SLACK_BOT_TOKEN}
             fi
-    - notify_slack:
-        message_text: "testing"
-        slack_channel: "tm-test"
-
     - notify_new_relic:
         target_env: << parameters.target_env >>
     - when:
@@ -1281,40 +1280,38 @@ commands:
         type: string
         default: ""
     steps:
-      - run:
-          name: Notify Slack
-          environment:
-              SLACK_BOT_TOKEN: << parameters.slack_bot_token >>
-          command: |
-            if [[ -n "<< parameters.message_text_file >>" ]]; then
-              MESSAGE=$(cat "<< parameters.message_text_file >>")
-            else
-              MESSAGE="<< parameters.message_text >>"
-            fi
-            
-            echo $MESSAGE_TEXT
-            # Ensure all parameters are provided
-            if [ -z "<< parameters.slack_bot_token >>" ] || [ -z "<< parameters.slack_channel >>" ] || [ -z "$MESSAGE_TEXT" ]; then
-              echo "Missing required parameters. Notification will not be sent."
-              exit 0
-            fi
+    - run:
+        name: Notify Slack
+        command: |
+          if [[ -z "<< parameters.message_text >>" ]]; then
+            MESSAGE="<< parameters.message_text >>"
+          else
+            MESSAGE=$(cat "<< parameters.message_text_file >>")            
+          fi
+          
+          echo "Sending: ${MESSAGE}"
+          # Ensure all parameters are provided
+          if [ -z "<< parameters.slack_bot_token >>" ] || [ -z "<< parameters.slack_channel >>" ] || [ -z "$MESSAGE" ]; then
+            echo "Missing required parameter. Notification will not be sent."
+            exit 0
+          fi
 
-            response=$(curl -s -X POST \
-              -H "Authorization: Bearer << parameters.slack_bot_token >>" \
-              -H 'Content-type: application/json;charset=utf-8' \
-              --data "{
-                \"channel\": \"<< parameters.slack_channel >>\",
-                \"text\": \"$MESSAGE_TEXT\"
-              }" \
-              https://slack.com/api/chat.postMessage)
-            ok=$(echo $response | jq -r '.ok')
-            error=$(echo $response | jq -r '.error')
-            if [ "$ok" != "true" ]; then
-              echo "Slack notification failed: $error"
-              exit 1
-            else
-              echo "Slack notification sent successfully"
-            fi
+          response=$(curl -s -X POST \
+            -H "Authorization: Bearer << parameters.slack_bot_token >>" \
+            -H 'Content-type: application/json;charset=utf-8' \
+            --data "{
+              \"channel\": \"<< parameters.slack_channel >>\",
+              \"text\": \"$MESSAGE\"
+            }" \
+            https://slack.com/api/chat.postMessage)
+          ok=$(echo $response | jq -r '.ok')
+          error=$(echo $response | jq -r '.error')
+          if [ "$ok" != "true" ]; then
+            echo "Slack notification failed: $error"
+            exit 1
+          else
+            echo "Slack notification sent successfully"
+          fi
 
   
   notify_slack_deploy:
