run with pg

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -157,14 +157,7 @@ jobs:
           name: Build backend assets
           command: yarn build
       - run: exit 1
-      - cf_backup:
-          auth_client_secret: PROD_AUTH_CLIENT_SECRET
-          cloudgov_username: CLOUDGOV_PROD_USERNAME
-          cloudgov_password: CLOUDGOV_PROD_PASSWORD
-          cloudgov_space: CLOUDGOV_PROD_SPACE
-          rds_service_name: ttahub-prod
-          s3_service_name: ttahub-db-backups
-          backup_prefix: production 
+      - cf_backup
 
   process_db:
     executor: docker-executor
@@ -455,7 +448,7 @@ jobs:
           destination: uncovered-lines
 
   test_e2e:
-    executor: docker-executor
+    executor: docker-postgres-executor
     steps:
       - attach_workspace:
           at: .
@@ -756,43 +749,6 @@ commands:
           name: Combine requirements.txt files to single file
           command: cat similarity_api/src/requirements.txt > << parameters.filename >>
  
-  run_with_db:
-    parameters:
-      command: 
-        type: string
-      artifacts:
-        type: string
-    steps:
-      # - run:
-      #     name: Install playwright dependencies
-      #     command: |
-      #       yarn add playwright
-      - run:
-          name: Start the server and watch logs
-          background: true
-          command: |
-            BYPASS_AUTH=true
-            CURRENT_USER_ID=5 
-            yarn start:ci
-      - run:
-          name: Run migrations ci
-          command: yarn db:migrate:ci
-      - run:
-          name: Seed database
-          command: yarn db:seed:ci
-      - run:
-          name: Wait for frontend to be running
-          command: ./bin/ping-server 3000     
-      - run:
-          name: Wait for backend to be running
-          command: |
-            lsof -i -P -n | grep LISTEN
-            ./bin/ping-server 8080 localhost /api
-      - run:
-          name: "Running: << parameters.command >>"
-          command: << parameters.command >>
-      - store_artifacts:
-          path: << parameters.artifacts >>
 
   sparse_checkout:
     description: "Checkout sparse directories from a specific branch."
@@ -1023,25 +979,18 @@ commands:
 
   cf_backup:
     description: "Backup database to S3"
-    parameters:
-      auth_client_secret: { type: env_var_name }
-      cloudgov_username: { type: env_var_name }
-      cloudgov_password: { type: env_var_name }
-      cloudgov_space: { type: env_var_name }
-      rds_service_name: { type: string }
-      s3_service_name: { type: string }
-      backup_prefix: { type: string }
     steps:
       - cf_automation_task:
-          auth_client_secret: << parameters.auth_client_secret >>
-          cloudgov_username: << parameters.cloudgov_username >>
-          cloudgov_password: << parameters.cloudgov_password >>
-          cloudgov_space: << parameters.cloudgov_space >>
+          auth_client_secret: ${AUTH_CLIENT_SECRET}
+          cloudgov_username: ${cg_username}
+          cloudgov_password: ${cg_password}
+          cloudgov_space: ${cg_space}
           task_name: "backup"
           task_command: "cd /home/vcap/app/db-backup/scripts; bash ./db_backup.sh"
           task_args: '["<< parameters.backup_prefix >>", "<< parameters.rds_service_name >>", "<< parameters.s3_service_name >>"]'
           config: "<< parameters.backup_prefix >>-backup"
           success_message: ':download::database: "<< parameters.backup_prefix >>" backup'
+
   cf_restore:
     description: "Restore backup database from S3"
     parameters:
@@ -1091,6 +1040,7 @@ commands:
           success_message: ':database: Restored data processed'
           directory: "./"
           timeout: "3000"
+
   cf_retention:
     description: "Delete Backup from S3 based on retention"
     parameters:
@@ -1111,3 +1061,194 @@ commands:
           task_args: '["<< parameters.backup_prefix >>", "<< parameters.s3_service_name >>"]'
           config: "<< parameters.backup_prefix >>-backup"
           success_message: ':database: "<< parameters.backup_prefix >>" retention processed'
+
+
+  cf_automation_task:
+    description: "Login to Cloud Foundry space, run automation task, and send notification"
+    parameters:
+      auth_client_secret:
+        description: "Name of CircleCi project environment variable that holds authentication client secret"
+        type: env_var_name
+      cloudgov_username:
+        description: "Name of CircleCi project environment variable that holds deployer username for Cloud Foundry space"
+        type: env_var_name
+      cloudgov_password:
+        description: "Name of CircleCi project environment variable that holds deployer password for Cloud Foundry space"
+        type: env_var_name
+      cloudgov_space:
+        description: "Name of CircleCi project environment variable that holds name of Cloud Foundry space to target for application deployment"
+        type: env_var_name
+      task_name:
+        description: "Name of the automation task to run"
+        type: string
+      task_command:
+        description: "Command to run for the automation task"
+        type: string
+      task_args:
+        description: "Arguments for the automation task"
+        type: string
+      config:
+        description: "Config prefix for the automation task"
+        type: string
+      success_message:
+        description: "Success message for Slack notification"
+        type: string
+      timeout:
+        description: "Max duration allowed for task"
+        type: string
+        default: "300"
+      directory:
+        description: 'directory to root to push'
+        type: string
+        default: "./automation"
+    steps:
+        - run:
+            command: |
+              echo "Running "<< parameters.task_command >>"
+      # - run:
+      #     name: Install Dependencies
+      #     command: |
+      #       set -e
+      #       set -u
+      #       set -o pipefail
+      #       set -o noglob
+      #       set -o noclobber
+
+      #       # update
+      #       sudo apt-get update
+      #       # Install uuid-runtime to have access to uuidgen
+      #       # Install pv wget
+      #       sudo apt-get install -y pv uuid-runtime wget coreutils jq
+
+      #       # Install Cloud Foundry CLI
+      #       wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
+      #       echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+      #       sudo apt-get update
+      #       sudo apt-get install -y cf8-cli
+      #       # Install plugin needed for connect-to-service
+      #       cf install-plugin -f https://github.com/cloud-gov/cf-service-connect/releases/download/v1.1.3/cf-service-connect_linux_amd64
+
+      #       # The line you want to ensure exists in the /etc/hosts file
+      #       line="127.0.0.1        localhost"
+
+      #       # Check if the line already exists
+      #       if ! grep -qF "$line" /etc/hosts; then
+      #           # If the line does not exist, append it
+      #           echo "$line" | sudo tee -a /etc/hosts > /dev/null
+      #           echo "Line added to /etc/hosts"
+      #       else
+      #           echo "Line already exists in /etc/hosts"
+      #       fi
+
+      #       # cleanup
+      #       sudo rm -rf /var/lib/apt/lists/*
+      # - run:
+      #     name: Login with service account
+      #     command: |
+      #       cf login -a << pipeline.parameters.cg_api >> \
+      #         -u ${<< parameters.cloudgov_username >>} \
+      #         -p ${<< parameters.cloudgov_password >>} \
+      #         -o << pipeline.parameters.cg_org >> \
+      #         -s ${<< parameters.cloudgov_space >>}
+      # - run:
+      #     name: Acquire Lock
+      #     command: |
+      #       chmod +x ./automation/ci/scripts/*-lock.sh
+      #       ./automation/ci/scripts/acquire-lock.sh \
+      #         "tta-automation" \
+      #         "<< pipeline.git.branch >>" \
+      #         "<< pipeline.number >>" \
+      #         "$CIRCLE_JOB"
+      # - run:
+      #     name: Start Log Monitoring
+      #     command: |
+      #       #!/bin/bash
+
+      #       CONTROL_FILE="/tmp/stop_tail"
+      #       rm -f $CONTROL_FILE
+
+      #       # Function to start tailing logs
+      #       start_log_tailing() {
+      #           echo "Starting cf logs for tta-automation..."
+      #           cf logs tta-automation &
+      #           TAIL_PID=$!
+      #       }
+
+      #       # Start tailing logs for the first time
+      #       start_log_tailing
+
+      #       # Monitor the cf logs process
+      #       while [ ! -f $CONTROL_FILE ]; do
+      #           # Check if the cf logs process is still running
+      #           if ! kill -0 $TAIL_PID 2>/dev/null; then
+      #               echo "cf logs command has stopped unexpectedly. Restarting..."
+      #               start_log_tailing
+      #           fi
+      #           sleep 1
+      #       done
+
+      #       # Kill the cf logs command
+      #       kill -9 $TAIL_PID
+      #       echo "cf logs command for tta-automation has been terminated."
+      #     background: true
+      # - run:
+      #     name: cf_lambda - script to trigger task
+      #     command: |
+      #       set -x
+      #       json_data=$(jq -n \
+      #         --arg directory "<< parameters.directory >>" \
+      #         --arg config "<< parameters.config >>" \
+      #         --arg task_name "<< parameters.task_name >>" \
+      #         --arg command "<< parameters.task_command >>" \
+      #         --arg timeout_active_tasks "<< parameters.timeout >>" \
+      #         --arg timeout_ensure_app_stopped "<< parameters.timeout >>" \
+      #         --argjson args '<< parameters.task_args >>' \
+      #         '{
+      #           directory: $directory,
+      #           config: $config,
+      #           task_name: $task_name,
+      #           command: $command,
+      #           timeout_active_tasks: $timeout_active_tasks,
+      #           timeout_ensure_app_stopped: $timeout_ensure_app_stopped,
+      #           args: $args
+      #         }')
+
+      #       # Set execute permission
+      #       find ./automation -name "*.sh" -exec chmod +x {} \;
+
+      #       ./automation/ci/scripts/cf_lambda.sh "$json_data"
+      # - run:
+      #     name: Generate Message
+      #     command: |
+      #       if [ ! -z "$CIRCLE_PULL_REQUEST" ]; then
+      #         PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
+      #         echo "<< parameters.success_message >> before PR <$CIRCLE_PULL_REQUEST|$PR_NUMBER> successful!" > /tmp/message_file
+      #       else
+      #         echo "<< parameters.success_message >> successful!" > /tmp/message_file
+      #       fi
+      # - notify_slack:
+      #     slack_bot_token: $SLACK_BOT_TOKEN
+      #     slack_channel: "acf-head-start-eng"
+      #     message_text_file: "/tmp/message_file"
+      # - run:
+      #     name: Release Lock
+      #     command: |
+      #       chmod +x ./automation/ci/scripts/*-lock.sh
+      #       ./automation/ci/scripts/release-lock.sh \
+      #         "tta-automation" \
+      #         "<< pipeline.git.branch >>" \
+      #         "<< pipeline.number >>" \
+      #         "$CIRCLE_JOB"
+      # - run:
+      #     name: Logout of service account
+      #     command: |
+      #       # Signal the log monitoring to stop
+      #       CONTROL_FILE="/tmp/stop_tail"
+      #       touch $CONTROL_FILE
+
+      #       # Wait for the log monitoring process to terminate
+      #       sleep 5
+
+      #       # Logout from Cloud Foundry
+      #       cf logout
+
