syntax

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1033,7 +1033,7 @@ commands:
             cf logs tta-smarthub-<< parameters.target_env >> --recent | grep ${TASK_NAME} | tee logs.txt
             echo "script exited with code:$rc"
             grep '"level":"error"' logs.txt
-            if [[ $? -eq 0 ]]; then echo "found error in logs" && exit 1; fi"
+            if [[ $? -eq 0 ]]; then echo "found error in logs" && exit 1; fi
             exit $rc
               
       - run:
